name: CI/CD Pipeline

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Backend Tests
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Test Backend
      env:
        DATABASE_URL: sqlite:///test.db #Fake env 
        SUPABASE_URL: https://test.supabase.co
        SUPABASE_ANON_KEY: test-key
        SUPABASE_JWT_SECRET: test-secret
        OPENAI_API_KEY: test-key
      run: |
        cd backend
        pip install -r requirements.txt
        pytest tests/ -v
    
    # Frontend Tests  
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Test Frontend
      run: |
        cd frontend
        npm install
        npm test -- --watchAll=false

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy
      run: echo "Deploy step"