name: CI/CD Pipeline

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test Backend
      run: |
        cd backend
        echo "Backend tests would run here"
    
    - name: Test Frontend  
      run: |
        cd frontend
        echo "Frontend tests would run here"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy
      run: echo "Deploy step"